---
name: sample-app-sinatra
provider: aws
region: eu-central-1

# bucket: sample-state
# Where to store the state by default in the user's home directory
# state:
#   provider: aws
#   bucket: project-name
#   key: abc/def

# Where to store the credentials
# secrets:
#   provider: aws
#   key: abc/def
#   path: ~/.stackmate/test123.yml.enc

stages:
  production:
    # application:
    #   type: application
    #   size: t2.nano
    #   storage: 20
    #   volumes:
    #     - size: 30
    #       name: test-volume
    #       mount: /var/www/test

    database:
      type: mysql
      size: db.t3.medium
      storage: 30
      # links:
      #   - application

    # loadbalancer:
    #   type: loadbalancer
    #   links:
    #     - application

    # routing:
    #   type: routing
    #   domains:
    #     - name: sinatra.ezploy.eu
    #       service: loadbalancer
    #     - name: www.sinatra.ezploy.eu
    #       type: CNAME
    #       value: sinatra.ezploy.eu
    #     - name: database.sinatra.ezploy.eu
    #       service: database

    # certificates:
    #   type: ssl
    #   domains:
    #     - "sinatra.ezploy.eu"
    #     - "*.sinatra.ezploy.eu"

  # Environment overrides - staging
  staging:
    from: production
    # skip:
    #   - routing
    #   - certificates
    # application:
    #   size: t2.large

  # Environment overrides - staging2
  staging2:
    from: staging
    # application:
    #   size: t2.xlarge
