---
name: sample-app-sinatra
# The default cloud provider to use
provider: aws
# The default region to deploy to
region: eu-central-1

# Where to store the state by default in the user's home directory
# state:
#   provider: aws
#   bucket: project-name
#   key: abc/def

# Where to store the credentials
# secrets:
#   provider: aws
#   key: abc/def
#   path: ~/.stackmate/test123.yml.enc

stages:
  - name: production
    services:
      - name: application
        type: application
        size: t2.nano
        storage: 20
        volumes:
          - size: 30
            name: test-volume
            mount: /var/www/test

      - name: database
        type: database
        size: db.t3.medium
        storage: 30
        profile: production
        links:
          - application

      - name: loadbalancer
        type: loadbalancer
        links:
          - application

    # routing:
    #   type: routing
    #   domains:
    #     - name: sinatra.ezploy.eu
    #       service: loadbalancer
    #     - name: www.sinatra.ezploy.eu
    #       type: CNAME
    #       value: sinatra.ezploy.eu
    #     - name: database.sinatra.ezploy.eu
    #       service: database

    # certificates:
    #   type: ssl
    #   domains:
    #     - "sinatra.ezploy.eu"
    #     - "*.sinatra.ezploy.eu"

  # Environment overrides - staging
  - name: staging
    copy: production
    # skip:
    #   - routing
    #   - certificates
    # application:
    #   size: t2.large

  # Environment overrides - staging2
  - name: staging2
    copy: staging
    # application:
    #   size: t2.xlarge
