name: End to End tests

on:
  push:
    branches:
      - main
      - falexandrou/end-to-end-tests # temporary

jobs:
  tests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-modules-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.3"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::827160314823:role/StackmateEngineTestsRunner
          aws-region: eu-central-1

      - name: Run tests
        run: npm run test:e2e
