name: End to End tests

on:
  push:
    branches:
      - main
      - falexandrou/e2e-tests

jobs:
  tests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.3"

      - name: Run tests
        run: yarn test:e2e
