name: Lint & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-modules-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Check for TypeScript errors
        run: npm run check:all

      - name: Check for circular imports
        run: npm run check:circular

      - name: Run the unit tests
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npm run test:unit
