name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint the project
        run: npm run lint

      - name: Install dependencies
        run: yarn install

      - name: Run the tests
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: yarn test:full
