name: Test & Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI: false

jobs:
  test:
    name: test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: yarn test

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          publish: yarn release
          title: 'chore: release packages'
          commit: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
